version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:lts
    working_directory: /home/circleci/hwsw-cicd-demo

jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v3-dependencies-{{ checksum "package.json" }}
            - v3-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v3-dependencies-{{ checksum "package.json" }}

      - run: npm run build

      - persist_to_workspace:
          root: /home/circleci
          paths:
            - hwsw-cicd-demo

  test:
    executor: node-executor
    steps:
      - attach_workspace:
          at: /home/circleci
      - run: npm test
      - run: npm run app-test

  test-echo:
    executor: node-executor
    steps:
      - attach_workspace:
          at: /home/circleci
      - run: ls
      - run: echo "alma"

workflows:
  version: 2.1
  build-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - test-echo:
          requires:
            - build
